# 配置tomcat端口号
server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能,利用微服务名进行路由
      routes:
        - id: payment_routh  #路由的ID,没有固定的规则,但要求唯一,建议配合服务名
          uri: lb://CLOUD-PAYMENT-SERVICE  #匹配后提供服务的路由地址
        #uri: http://localhost:8001 #匹配后提供服务的路由地址
          predicates:
          - Path=/payment/get/**  #断言:路径相匹配的进行路由
        - id: payment_routh2  #路由的ID,没有固定的规则,但要求唯一
          uri: lb://CLOUD-PAYMENT-SERVICE  #匹配后提供服务的路由地址
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          predicates:
          - Path=/payment/lb/**  #断言:路径相匹配的进行路由
#          - After=2021-04-29T18:41:00.226+08:00[Asia/Shanghai]
#          - Cookie=username,test
#          - Header=X-Request-Id, \d+
#          filter:
#            - AddRequestHeader=X-Request-red,111
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    #表示自己是否将自己注册进eureka server,默认为true
    register-with-eureka: true
    #是否从eureka server抓取已有的注册信息,默认为true.单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

