# 配置tomcat端口号
server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  endpoints:
    web:
      exposure:
        include: "*"