# 配置tomcat端口号
server:
  port: 3344

spring:
  application:
    name: cloud-config-server  #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
#          uri: git@github.com:wangjianping0/cloud20210322config.git     #GitHub上面的git仓库名字
          uri: https://wangjianping0:wang4jian8ping5@github.com/wangjianping0/cloud20210322config.git     #GitHub上面的git仓库名字
          #搜索目录
          search-paths:
            - cloud20210322config
          timeout: 10
      #读取分支
      label: master
#rabbitmq相关配置
  rabbitmq:
    host: 47.103.118.102
    port: 5672
    username: guest
    password: guest
#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/


#rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'