# 配置tomcat端口号
server:
  port: 2002

# 配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.98.229.181:3306/seata_storage
    username: root
    password: wangjianping
  application:
    name: seata-storage-service
  cloud:
    nacos:
      discovery:
        server-addr: 47.103.118.102:8848
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: fsp_tx_group
# 配置日志
logging:
  level:
    io:
      seata: info

feign:
  hystrix:
    enabled: true

mybatis:
  mapperLocations: classpath:mapper/*.xml