# 配置tomcat端口号
server:
  port: 8001

# 配置数据源
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://39.98.229.181:3306/cloudproject?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: wangjianping



eureka:
  client:
    #表示自己是否将自己注册进eureka server,默认为true
    register-with-eureka: true
    #是否从eureka server抓取已有的注册信息,默认为true.单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    #主机名称
    instance-id: payment8001
    prefer-ip-address: true   #访问路径可显示ip地址
    #eureka客户端向服务器发送心跳的时间间隔,单位为秒(默认是30秒)
    lease-renewal-interval-in-seconds: 30
    #eureka服务端在收到最后一次心跳后等待的时间上限,单位为秒(默认是90秒),超时将剔除服务
    lease-expiration-duration-in-seconds: 90
# 配置mybatis
mybatis:
  # 配置类型别名包扫描
  type-aliases-package: org.example.springcloud.entity   #所有Entity别名类所在包
  # 配置sql语句映射文件路径
  mapper-locations:
    - classpath:mapper/*.xml
  # 驼峰映射
#  configuration:
#    map-underscore-to-camel-case: true

# 配置日志
#logging:
#  level:
#    com.xxx: debug