# 配置tomcat端口号
server:
  port: 2001

# 配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.98.229.181:3306/seata_order
    username: root
    password: wangjianping
  application:
    name: seata-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 47.103.118.102:8848
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: fsp_tx_group
# 配置日志
logging:
  level:
    io:
      seata: info

feign:
  hystrix:
    enabled: true

mybatis:
  mapperLocations: classpath:mapper/*.xml


#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #  指的是建立连接所用的时间,适用于网络状况正常的情况下,两端连接所用时间
  ReadTimeout: 5000
  #  指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000