# 配置tomcat端口号
server:
  port: 8004

# 服务别名,注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-payment-service
  cloud:
    zookeeper:
      connect-string: 47.103.118.102:2181



eureka:
  client:
    #表示自己是否将自己注册进eureka server,默认为true
    register-with-eureka: true
    #是否从eureka server抓取已有的注册信息,默认为true.单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    #主机名称
    instance-id: payment8002
    prefer-ip-address: true   #访问路径可显示ip地址
# 配置mybatis
mybatis:
  # 配置类型别名包扫描
  type-aliases-package: org.example.springcloud.entity   #所有Entity别名类所在包
  # 配置sql语句映射文件路径
  mapper-locations:
    - classpath:mapper/*.xml