# 配置tomcat端口号
server:
  port: 8001
spring:
  application:
    name: cloud-provider-hystrix-payment
# 配置数据源

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://39.98.229.181:3306/cloudproject?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: wangjianping
eureka:
  client:
    #表示自己是否将自己注册进eureka server,默认为true
    register-with-eureka: true
    #是否从eureka server抓取已有的注册信息,默认为true.单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

# 配置mybatis
mybatis:
  # 配置类型别名包扫描
  type-aliases-package: org.example.springcloud.entity   #所有Entity别名类所在包
  # 配置sql语句映射文件路径
  mapper-locations:
    - classpath:mapper/*.xml