# 配置tomcat端口号
server:
  port: 80

spring:
  application:
    name: consul-customer-order
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
#        hostname: 127.0.0.1

